app = "shorouk-rental"

[build]

[env]
  DATA_DIR = "/data"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

[[mounts]]
  source = "shorouk_data"
  destination = "/data"
